---
ENV: development

WEBSITE_PATH: /var/www/javnikonkursi.com
BACKEND_PORT: 3000
FRONTEND_PORT: 80

GIT_BRANCH: develop
PROJECT_ROOT: /home/node/code/javnikonkursi.com
FRONTEND_PATH: services/frontend
BACKEND_PATH: services/backend
