version: "3.7"
services:
  db:
    image: postgres:13
    volumes:
      - db_volume:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    env_file:
      - ../.env

  backend:
    depends_on:
      - db
    volumes:
      - ..:/home/node/code
      # - ../backend/node_modules:/home/node/code/backend/node_modules
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
      args:
        ENV: development
    expose:
      - 3000
    restart: always
    env_file:
      - ../.env

  frontend:
    depends_on:
      - db
      - backend
    volumes:
      - ..:/home/node/code/
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    expose:
      - 8080
    restart: always
    env_file:
      - ../.env
  proxy:
    image: nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ../nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
    restart: always
    env_file:
      - ../.env

volumes:
  db_volume: {}
