version: "3.7"
services:
  backend:
    build:
      args:
        ENV: dev-server
    command: ["npm", "run", "start:watch"]
    ports:
      - 3000:3000
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile.devServer
