version: "3.7"
services:
  backend:
    build:
      args:
        ENV: production
    command: ["yarn", "--cwd", "services/backend", "start"]
  frontend:
    build:
      args:
        ENV: production
