version: "3.7"
services:
  backend:
    build:
      args:
        ENV: dev-server
    command: ["yarn", "--cwd", "services/backend", "start:watch"]
    ports:
      - 3000:3000
  frontend:
    build:
      dockerfile: ./services/frontend/Dockerfile.devServer
