---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_host }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/HasanJoldic/javnikonkursi.com.git"
        dest: {{ PROJECT_ROOT }}
        version: "{{ GIT_BRANCH }}"

    - name: Install Nginx
      apt:
        name: nginx=1.18.0

    - name: Install node and npm
      apt:
        name: "{{ item }}"
      loop:
        - node=16.*
        - npm=8.*

    - name: Install yarn
      community.general.npm:
        name: yarn=1.*
        global: yes
        version: "1.22.5"

    - name: Install node modules
      community.general.yarn:
        path: {{ PROJECT_ROOT }}
        production: "{{ 'yes' if ENV == 'production' else 'no' }}"

    - name: Build packages
      ansible.builtin.shell:
        cmd: yarn workspaces run build
        chdir: {{ PROJECT_ROOT }}

    - name: Copy website files to the server's document root
      copy:
        src: {{ PROJECT_ROOT }}/services/build
        dest: {{ WEBSITE_PATH }}
        mode: preserve

    - name: Apply Nginx template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: "80"
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
